# Generated by Django 6.0 on 2025-12-21 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('eligibility', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('button_text', models.CharField(default='Start Writing', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rules', models.TextField(blank=True)),
                ('submission_guidelines', models.TextField(blank=True)),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('max_words', models.IntegerField(default=2000)),
                ('min_words', models.IntegerField(default=500)),
            ],
            options={
                'ordering': ['order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('html_content', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_count', models.IntegerField(default=0)),
                ('current_paragraph', models.IntegerField(default=0)),
                ('is_paragraph_mode', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.essaycompetition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LockedParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_index', models.IntegerField()),
                ('content', models.TextField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_paragraphs', to='competition.essay')),
            ],
            options={
                'ordering': ['paragraph_index'],
                'unique_together': {('essay', 'paragraph_index')},
            },
        ),
    ]
