# Generated by Django 6.0 on 2025-12-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='current_paragraph',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='is_paragraph_mode',
        ),
        migrations.DeleteModel(
            name='LockedParagraph',
        ),
    ]
