# Generated by Django 6.0 on 2025-12-23 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_remove_essay_current_paragraph_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Essays'},
        ),
        migrations.AddField(
            model_name='essay',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='character_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='grammar_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='originality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='plagiarism_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='essay',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('winner', 'Winner'), ('runner_up', 'Runner Up')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='essay',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
