# Generated by Django 6.0 on 2026-02-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_essay_options_essay_admin_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='reviewed_at',
            new_name='analyzed_at',
        ),
        migrations.AddField(
            model_name='essay',
            name='cohesion_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='cohesion_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='keyword_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='pronoun_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='structure_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='topic_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='transition_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
