# Generated by Django 6.0 on 2026-02-03 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_rename_reviewed_at_essay_analyzed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay',
            options={'ordering': ['-total_score']},
        ),
        migrations.AlterModelOptions(
            name='essaycompetition',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='essay',
            old_name='analyzed_at',
            new_name='evaluated_at',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='character_count',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='cohesion_feedback',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='keyword_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='language',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='originality_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='plagiarism_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='pronoun_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='transition_score',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='word_count',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='evaluation_criteria',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='order',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='submission_guidelines',
        ),
        migrations.AddField(
            model_name='essaycompetition',
            name='topic',
            field=models.TextField(default='General Topic', help_text='Main topic/theme for relevance evaluation'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='cohesion_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='essay',
            name='grammar_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='essay',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='essay',
            name='structure_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='essay',
            name='topic_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='essay',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['status', 'total_score'], name='competition_status_5db863_idx'),
        ),
    ]
