# Generated by Django 6.0 on 2026-02-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_alter_essay_options_alter_essaycompetition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaycompetition',
            name='topic',
            field=models.TextField(help_text='Main topic/theme for relevance evaluation'),
        ),
    ]
