# Generated by Django 6.0 on 2026-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_essaycompetition_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='topic_score',
            new_name='title_relevance_score',
        ),
        migrations.RemoveField(
            model_name='essaycompetition',
            name='topic',
        ),
        migrations.AlterField(
            model_name='essaycompetition',
            name='max_words',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='essaycompetition',
            name='min_words',
            field=models.IntegerField(default=250),
        ),
    ]
