# Generated by Django 6.0 on 2026-02-05 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_rename_topic_score_essay_title_relevance_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='essay',
            name='stored_character_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='stored_word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['stored_word_count'], name='competition_stored__aa7b43_idx'),
        ),
    ]
