# Generated by Django 6.0 on 2026-02-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_essay_html_content_essay_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay',
            options={'ordering': ['-total_score', '-created_at'], 'verbose_name': 'Essay', 'verbose_name_plural': 'Essays'},
        ),
        migrations.AlterModelOptions(
            name='essaycompetition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterField(
            model_name='essay',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='competition.essaycompetition'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='essay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['competition', 'status'], name='competition_competi_cebf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='essay',
            index=models.Index(fields=['user', 'competition'], name='competition_user_id_967e56_idx'),
        ),
    ]
