# Generated by Django 6.0 on 2026-02-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='identydoc',
            new_name='identity_doc',
        ),
    ]
